### ISSUE TITLE
skype jss-recipe version

### ISSUE THREAD

**Issue by daroloson** [autopkg/jss-recipes#122]
Might not be an issue with your code but best place to ask.

I'm using the jss-recipe for Skype with Auto Update Magic
and it installs it over and over again.

I think the problem is that one side uses the full version 7.53.0.580
and the other side uses just 7.53 and so they never match so
it continually installs. Any ideas appreciated.

**Comment by homebysix** [comment]
Might have been solved by this: https://github.com/autopkg/homebysix-recipes/pull/122

Can you try again now?

**Comment by homebysix** [comment]
@daroloson - What's the verdict?

**Comment by daroloson** [comment]
bash-3.2# jamf policy -event autoupdate-Skype

Checking for policies triggered by "autoupdate-Skype" for user "mfadmin"...

Executing Policy Auto Update Skype

Mounting JSSshare-L-smb

Installing Skype-7.59.0.37.pkg...

Successfully installed Skype-7.59.0.37.pkg.

Unmounting file server...

Submitting log to https://MyJSS:8443/

bash-3.2# jamf policy -event autoupdate-Skype

Checking for policies triggered by "autoupdate-Skype" for user "mfadmin"...

Executing Policy Auto Update Skype

Mounting JSSshare-L-smb

Installing Skype-7.59.0.37.pkg...

Successfully installed Skype-7.59.0.37.pkg.

Unmounting file server...

Submitting log to https://MyJSS:8443/

bash-3.2#


Seems to still be installing multiple times

but I'm unsure enough about the process

that I may not have updated all the required pieces.


________________________________

**Comment by daroloson** [comment]
So I really don't understand how a change in the Spotify recipe

is supposed to change how the Skype recipe behaves.

________________________________

**Comment by homebysix** [comment]
@daroloson - Sorry, got confused because there's a similar issue with Spotify.

All AutoPkg recipes and templates associated with Skype should be using CFBundleVersion (7.59.0.37) instead of CFBundleShortVersionString (7.59). Can you post the criteria of your JSSImporter-generated Skype smart group?

**Comment by georgecm12** [comment]
I'm rather surprised, given how old this issue is, but this appears to persist. 

After a quick review, the problem may be within the parent recipe (com.github.autopkg.pkg.Skype). Running that recipe by itself produces a package named "Skype-8.60.pkg" (as of 5/21/20), which suggests to me that %VERSION% is being set to CFBundleShortVersionString, not the CFBundleVersion (8.60.0.76).

The criteria of the JSSImporter-generated Skype smart group is as follows:
**Application Title** is **Skype.app**
and **Skype Version** is not **8.60**
and **Skype Version** is not (blank)
and **Computer Group** member of **Testing**

**Comment by homebysix** [comment]
Closing issue due to [repo deprecation and archive](https://github.com/autopkg/jss-recipes/issues/267).
