### ISSUE TITLE
Skype recipe out of date

### ISSUE THREAD

**Issue by daroloson** [autopkg/jss-recipes#174]
I think I forced AutoPkgr to get the new recipe but it didn't help.

RecipeOverrides$ fgrep 10. Skype*
Skype.jss.recipe:		<string>10.12.x,10.11.x,10.10.x,10.9.x</string>
RecipeOverrides$ fgrep 10. Skype*
Skype.jss.recipe:		<string>10.13.x,10.12.x,10.11.x,10.10.x,10.9.x</string>

**Comment by homebysix** [comment]
Hi @daroloson - I'm not clear about what issue you're experiencing. Is your recipe downloading an old version of Skype, or is your override package requirements preventing installation on 10.13?

The former issue is probably not related to the Skype jss recipe, and the latter issue can be fixed by adjusting the `OS_REQUIREMENTS` string in your override.

**Comment by daroloson** [comment]
From https://github.com/autopkg/jss-recipes/blob/master/Skype/Skype.jss.recipe

> \<key\>OS_REQUIREMENTS\</key\>
> \<string\>10.13.x,10.12.x,10.11.x,10.10.x,10.9.x\</string\>

so if someone new uses this, it will not install under 10.14

**Comment by homebysix** [comment]
Hi @daroloson - Thanks for clarifying. That string hasn't been updated for two reasons:

- Rather than unilaterally updating all 10.13-compatible apps to include 10.14, we depend on pull requests from the community members who deploy these apps. If you deploy Skype via Jamf and can confirm that adding `10.14.x` to the requirements successfully installs the app on 10.14 Macs, please do submit a PR for that change.
- Regardless of whether the OS requirements in the jss-recipes repository are up to date or not, `OS_REQUIREMENTS` is an input key that administrators can (and should) override locally with their preferred value.
