### ISSUE TITLE
MySQL WorkBench 8.0.19 has OS Version Restrictions

### ISSUE THREAD

**Issue by nc-keopraseuths** [autopkg/jss-recipes#203]
MySQL Workbench does not have 10.14.x or 10.15.x included in the operating system requirement. Is this on purpose? Should I create an override of our own and lift/add the OS version requirement?

**Comment by homebysix** [comment]
Hi @nc-keopraseuths - We don't go out of our way to keep OS requirements up to date here because they change frequently and because they can be redefined easily in overrides.

However, I'd be willing to accept a PR for updated requirements, if you have a minute to submit one. That would certainly help people who are overriding the recipe for the first time.
