### ISSUE TITLE
Skype version/shortversion

### ISSUE THREAD

**Issue by Thomgi** [autopkg/jss-recipes#4]
Hi,

I'm not sure this is a bug, let me first explain.

Since few weeks now, Skype doesn't really work well in JSS with JSSImporter due to confusion of version/shortversion.

- Autopkgr download last Skype available, and create a pkg : 7.9.0.746 at this moment
- JSSImporter imports it on JSS, and edit smart-group and policies.

By editing the smart group in the JSS, it seek computers for Skype version "7.9.0.746", quite normal.

But in fact, if you take a look on the Skype app, it version is 7.9 which in fact is the "CFBundleShortVersionString" on the info.plist inside the App, where "7.9.0.746" is the "CFBundleVersion".

At the end, I have a smart group that seek for version 7.9.0.746 and find only 7.9 and reinstall policy on all computer all the time. But if we change criteria to seek for version 7.9 only, a lot of client computers won't have the last 7.9 version of skype…

Is there a way to fix that kind of bug ?

**Comment by Thomgi** [comment]
In fact I've found how to do, I create an extension attribute to seek for real version installed on computer and put criteria on that extension attribute.

**Comment by sheagcraig** [comment]
Hey @Thomgi. Actually, that's a really useful point. I'm aware of this issue and what's going on-and the problem really is that the Casper inventory is using one version, rather than using the most complete version available. And you are correct in handling it with an extension attribute.

I'll add the creation of and management of that extension attribute for Skype to the todo list, since I would like handling of it to be automatic for everyone!

**Comment by sheagcraig** [comment]
Done.

**Comment by Thomgi** [comment]
If it could help you, here is the content of my skype extension attribute :
```
#!/bin/bash

SkypeVersion=$(defaults read /Applications/Skype.app/Contents/Info.plist CFBundleVersion)

echo "<result>$SkypeVersion</result>"

exit 0
```

**Comment by Thomgi** [comment]
Oh I do not see that you already do the job. Thanks for anything !
