### ISSUE TITLE
Name over ride not working for yo recipe...

### ISSUE THREAD

**Issue by everetteallen** [autopkg/jss-recipes#9]
Everything else works but the override below does not rename the package.
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Identifier</key>
	<string>local.jss.UNCSystem-AutoPKG-yo</string>
	<key>Input</key>
	<dict>
		<key>CATEGORY</key>
		<string>aaUNCSystem-Test</string>
		<key>GROUP_NAME</key>
		<string></string>
		<key>GROUP_TEMPLATE</key>
		<string></string>
		<key>NAME</key>
		<string>UNCSystem-AutoPKG-yo</string>
		<key>POLICY_CATEGORY</key>
		<string></string>
		<key>POLICY_TEMPLATE</key>
		<string></string>
		<key>SELF_SERVICE_DESCRIPTION</key>
		<string>yo is a command-line utility for presenting native OS X persistent notifications with custom text, icons, sounds, and actions.</string>
		<key>SELF_SERVICE_ICON</key>
		<string></string>
	</dict>
	<key>ParentRecipe</key>
	<string>com.github.jss-recipes.jss.yo</string>
</dict>
</plist>
```

**Comment by sheagcraig** [comment]
Hey @everetteallen Do you mean the package file itself doesn't get renamed, or the package object on the JSS?

A full sanitized `autopkg run -vvvv yo.jss` would probably help solve this one.

**Comment by everetteallen** [comment]
Both Actually. 
![screen shot 2015-07-28 at 1 46 48 pm](https://cloud.githubusercontent.com/assets/5263924/8938890/4266ec60-352f-11e5-80f5-1e4179a91ae3.png)

**Comment by sheagcraig** [comment]
Reviewing the code path for what (I imagine) you are doing gives me an answer.

Parent Recipes usually name packages with a concatenation of %NAME%-%version%. However, in yo's case, there's already a built package on GitHub that the download recipe grabs. It doesn't rename it, it basically just downloads it.

Let me see if I can add either a package recipe or an extra processor to the download recipe to allow overriding NAME to rename the package.

ALSO, it makes me realize that, while you can update an existing package's category, os_requirements, notes, or info, you can't change it's name after it has been created (with JSSImporter). This should probably get fixed as well.

**Comment by everetteallen** [comment]
So for us it really is the Display Name that's important and I have had even less luck with setting that in Overrides.  However it looks like JAMF might be moving away from display names so best time spent would be on package renames.  We just want to use a concatenation of %Prefix%-%NAME%-%version% for all packages.

**Comment by sheagcraig** [comment]
I'm uncomfortable with the idea of having display name and package name differ, and if as you say JAMF is going away from display name, that would cement it for me.

So in yo's case, it's easy to add in a renaming or copying or moving step, or create a package recipe which does that.

But almost all recipes seem to build their package names by doing %NAME%-%version%, so I think the only real solution is to override `NAME` for all recipes to include the prefix you want. (Which is probably what you already do).

This is why JSSImporter uses a separate `prod_name` argument, as, while in most cases using the value of `NAME` will be what is wanted, places that want to put a prefix on are going to need to be able to override `NAME for the package filename. `prod_name` is used for the smart group criteria or extension attributes needed to determine inventory status of the app. I know this isn't an issue for your setup, since you're only pushing packages up, but I can imagine an organization that would want to prefix their package filenames AND make smart groups / extension attributes.

So, is this really just an issue with the yo recipe for y'all right now? Or do you see this issue with any other recipes?

**Comment by everetteallen** [comment]
I see this issue with several other packages.  The ones I see so far from autopkg/jss are
Office2011Update, OracleJava7, OracleJava8, Google Earth, and FileZilla.  I also saw it on one of the R recipes but will have to check which one.

**Comment by sheagcraig** [comment]
I'll dig into those recipes and see what I can do!

**Comment by MScottBlake** [comment]
In the download recipe, if you give the URLDownloader a `filename` argument of something like `%NAME%-%version%.pkg`, then the name given will travel through. I have not tested this, so I can't confirm that `%version%` will be correct.
```
<key>Processor</key>
<string>URLDownloader</string>
<key>Comment</key>
<string>Download latest yo package.</string>
<key>Arguments</key>
<dict>
  <key>filename</key>
  <string>%NAME%-%version%.pkg</string>
</dict>
```

**Comment by homebysix** [comment]
@MScottBlake, if this is still an outstanding issue, could you submit a PR to Shea's Yo.download recipe with the above fix?
